In [1]:
emp = {'name':['Kiran','Krish','John'],'gender':['male','male','male'],'email':['abc@gmail.com','def@gmail.com','ghi@gmail.com']}

In [2]:
emp

{'name': ['Kiran', 'Krish', 'John'],
 'gender': ['male', 'male', 'male'],
 'email': ['abc@gmail.com', 'def@gmail.com', 'ghi@gmail.com']}

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(emp)

In [5]:
df

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [17]:
fc = (df['name']=='Kiran')

In [15]:
df.index = [0,1,2]

In [16]:
df[fc]

    name gender          email
0  Kiran   male  abc@gmail.com
1  Kiran   male  def@gmail.com
2  Kiran   male  ghi@gmail.com

In [10]:
df

    name gender          email
0  Kiran   male  abc@gmail.com
1  Kiran   male  def@gmail.com
2  Kiran   male  ghi@gmail.com

In [11]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
#alter the index
df.index = ['a','b','c']

In [13]:
df

    name gender          email
a  Kiran   male  abc@gmail.com
b  Kiran   male  def@gmail.com
c  Kiran   male  ghi@gmail.com

In [20]:
df.columns

Index(['name', 'gender', 'email'], dtype='object')

In [21]:
#rename all columns
df.columns = ['emp_name','gender','emp_email']

In [22]:
df

  emp_name gender      emp_email
0    Kiran   male  abc@gmail.com
1    Kiran   male  def@gmail.com
2    Kiran   male  ghi@gmail.com

In [25]:
#rename specific column names
df.rename(columns = {'emp_name':'name','emp_email':'email_id'},inplace=True)

In [26]:
df

    name gender       email_id
0  Kiran   male  abc@gmail.com
1  Kiran   male  def@gmail.com
2  Kiran   male  ghi@gmail.com

In [28]:
# update a full row
df.loc[0] = ['Emily','Female','emily@gmail.com']

In [29]:
df

    name  gender         email_id
0  Emily  Female  emily@gmail.com
1  Kiran    male    def@gmail.com
2  Kiran    male    ghi@gmail.com

In [30]:
# update value of one row
df.loc[0,'name'] = 'John'

In [31]:
df

    name  gender         email_id
0   John  Female  emily@gmail.com
1  Kiran    male    def@gmail.com
2  Kiran    male    ghi@gmail.com

In [43]:
#update value of two rows
df.loc[0,['name','email_id']] = ['Michael','Michael@gmail.com']

In [41]:
del df['email']

In [44]:
df

      name  gender           email_id
0  Michael  Female  Michael@gmail.com
1    Kiran    male      def@gmail.com
2    Kiran    male      ghi@gmail.com

In [58]:
df['name'].apply(len)

0    7
1    5
2    5
Name: name, dtype: int64

In [59]:
df['gender'].apply(len)

0    6
1    4
2    4
Name: gender, dtype: int64

In [60]:
def update_email(email_id):
    return email_id.upper()

In [63]:
#apply udf to only specific column
df['email_id'] = df['email_id'].apply(update_email)

In [64]:
df

      name  gender           email_id
0  Michael  Female  MICHAEL@GMAIL.COM
1    Kiran    male      DEF@GMAIL.COM
2    Kiran    male      GHI@GMAIL.COM

In [65]:
# apply udf to all columns
df.applymap(update_email)

      name  gender           email_id
0  MICHAEL  FEMALE  MICHAEL@GMAIL.COM
1    KIRAN    MALE      DEF@GMAIL.COM
2    KIRAN    MALE      GHI@GMAIL.COM

In [66]:
# apply - to a series
# applymap - to multiple serieses (dataframe)

In [69]:
#apply string functions directly on series objects like columns
df['name'] = df['name'].str.upper()

In [70]:
df

      name  gender           email_id
0  MICHAEL  Female  MICHAEL@GMAIL.COM
1    KIRAN    male      DEF@GMAIL.COM
2    KIRAN    male      GHI@GMAIL.COM

In [71]:
df['gender'] = df['gender'].str.upper()

In [72]:
df

      name  gender           email_id
0  MICHAEL  FEMALE  MICHAEL@GMAIL.COM
1    KIRAN    MALE      DEF@GMAIL.COM
2    KIRAN    MALE      GHI@GMAIL.COM

In [74]:
df

      name  gender           email_id
0  MICHAEL    True  MICHAEL@GMAIL.COM
1    KIRAN    True      DEF@GMAIL.COM
2    KIRAN    True      GHI@GMAIL.COM

In [76]:
df

      name  gender           email_id
0  MICHAEL    True  MICHAEL@GMAIL.COM
1    KIRAN    True      DEF@GMAIL.COM
2    KIRAN    True      GHI@GMAIL.COM

In [77]:
emp = {'name':['Kiran','Krish','John'],'gender':['male','male','male'],'email':['abc@gmail.com','def@gmail.com','ghi@gmail.com']}

In [78]:
df=pd.DataFrame(emp)
df

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [79]:
# add a new column
df['salary'] = 10000

In [80]:
df

    name gender          email  salary
0  Kiran   male  abc@gmail.com   10000
1  Krish   male  def@gmail.com   10000
2   John   male  ghi@gmail.com   10000

In [81]:
df['name_gender'] = df['name'] + ' ' +  df['gender']

In [82]:
df

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com   10000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [83]:
# update salary to emp whose name = 'Kiran'
fc = (df['name']=='Kiran')
df.loc[fc,'salary']=5000

In [84]:
df

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [85]:
# ddelete rows
df.drop(index=0)

    name gender          email  salary name_gender
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [86]:
df

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [87]:
#df.drop(index=0,inplace=True)

In [88]:
df

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [89]:
fc=(df['salary']>5000)
fc

0    False
1     True
2     True
Name: salary, dtype: bool

In [91]:
df.drop(index=df[fc].index)

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male

In [93]:
# drop a column
df.drop(columns='name_gender')

    name gender          email  salary
0  Kiran   male  abc@gmail.com    5000
1  Krish   male  def@gmail.com   10000
2   John   male  ghi@gmail.com   10000

In [94]:
#sorting asc
df.sort_values(by='name')

    name gender          email  salary name_gender
2   John   male  ghi@gmail.com   10000   John male
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male

In [95]:
#sorting desc
df.sort_values(by='salary',ascending=False)

    name gender          email  salary name_gender
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male
0  Kiran   male  abc@gmail.com    5000  Kiran male

In [96]:
#sort based on two columns
df.sort_values(by=['gender','salary'])

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [97]:
df.sort_values(by=['gender','salary'],ascending=[False,True])

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [98]:
df.sort_index()

    name gender          email  salary name_gender
0  Kiran   male  abc@gmail.com    5000  Kiran male
1  Krish   male  def@gmail.com   10000  Krish male
2   John   male  ghi@gmail.com   10000   John male

In [99]:
df.sort_index(ascending=False)

    name gender          email  salary name_gender
2   John   male  ghi@gmail.com   10000   John male
1  Krish   male  def@gmail.com   10000  Krish male
0  Kiran   male  abc@gmail.com    5000  Kiran male