In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\kgunturu\\Desktop\\Python\\nyc_weather.csv")

In [5]:
weather_data={
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/5/2017'],
    'temperature':[32,35,28,24,32,31],
    'wndspeed': [6,7,2,7,4,2],
    'event': ['Rain','Sunny','Snow','Snow','Rain','Sunny']
}

In [6]:
df=pd.DataFrame(weather_data)

In [7]:
df

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [8]:
df.shape

(6, 4)

In [9]:
rows, columns = df.shape

In [10]:
rows

6

In [11]:
columns

4

In [12]:
df.head()

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain

In [13]:
df.head(2)

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny

In [14]:
df.tail()

        day  temperature  wndspeed  event
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [15]:
df.tail(1)

        day  temperature  wndspeed  event
5  1/5/2017           31         2  Sunny

In [16]:
df[2:5]

        day  temperature  wndspeed event
2  1/3/2017           28         2  Snow
3  1/4/2017           24         7  Snow
4  1/5/2017           32         4  Rain

In [17]:
df[:]

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [19]:
df.columns

Index(['day', 'temperature', 'wndspeed', 'event'], dtype='object')

In [20]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/5/2017
Name: day, dtype: object

In [21]:
df.event #df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
type(df['event'])

pandas.core.series.Series

In [24]:
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/5/2017

In [28]:
df['temperature'].min()

24

In [29]:
df['temperature'].max()

35

In [30]:
df['temperature'].std()

3.8297084310253524

In [31]:
df.describe

<bound method NDFrame.describe of         day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny>

In [32]:
df.describe()

       temperature  wndspeed
count     6.000000  6.000000
mean     30.333333  4.666667
std       3.829708  2.338090
min      24.000000  2.000000
25%      28.750000  2.500000
50%      31.500000  5.000000
75%      32.000000  6.750000
max      35.000000  7.000000

In [33]:
df[df.temperature>=32]

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
4  1/5/2017           32         4   Rain

In [37]:
df[df.temperature==df.temperature.max()]

        day  temperature  wndspeed  event
1  1/2/2017           35         7  Sunny

In [42]:
df.wndspeed==2

0    False
1    False
2     True
3    False
4    False
5     True
Name: wndspeed, dtype: bool

In [44]:
df[df.event==df.event=='Rain']

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [46]:
df.event=='Rain'

0     True
1    False
2    False
3    False
4     True
5    False
Name: event, dtype: bool

In [47]:
df[df.event=='Rain']

        day  temperature  wndspeed event
0  1/1/2017           32         6  Rain
4  1/5/2017           32         4  Rain

In [48]:
df[df.temperature==df['temperature'].max()] # use this syntax when there are any spaces in the column

        day  temperature  wndspeed  event
1  1/2/2017           35         7  Sunny

In [49]:
df[df.temperature==df['temperature'].min()]

        day  temperature  wndspeed event
3  1/4/2017           24         7  Snow

In [52]:
df['temperature']==24

0    False
1    False
2    False
3     True
4    False
5    False
Name: temperature, dtype: bool

In [53]:
df.temperature==24

0    False
1    False
2    False
3     True
4    False
5    False
Name: temperature, dtype: bool

In [54]:
df[df.temperature==24]

        day  temperature  wndspeed event
3  1/4/2017           24         7  Snow

In [55]:
df[df.temperature==df.temperature.max()]

        day  temperature  wndspeed  event
1  1/2/2017           35         7  Sunny

In [56]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/5/2017           31

In [57]:
df[['day','temperature']][df.temperature==df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [58]:
df

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [60]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [61]:
df.set_index('day', inplace=True)

In [62]:
df

          temperature  wndspeed  event
day
1/1/2017           32         6   Rain
1/2/2017           35         7  Sunny
1/3/2017           28         2   Snow
1/4/2017           24         7   Snow
1/5/2017           32         4   Rain
1/5/2017           31         2  Sunny

In [65]:
df.loc['1/4/2017']

temperature      24
wndspeed          7
event          Snow
Name: 1/4/2017, dtype: object

In [66]:
df.reset_index()

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [67]:
df.reset_index(inplace=True)

In [68]:
df

        day  temperature  wndspeed  event
0  1/1/2017           32         6   Rain
1  1/2/2017           35         7  Sunny
2  1/3/2017           28         2   Snow
3  1/4/2017           24         7   Snow
4  1/5/2017           32         4   Rain
5  1/5/2017           31         2  Sunny

In [69]:
df.describe()

       temperature  wndspeed
count     6.000000  6.000000
mean     30.333333  4.666667
std       3.829708  2.338090
min      24.000000  2.000000
25%      28.750000  2.500000
50%      31.500000  5.000000
75%      32.000000  6.750000
max      35.000000  7.000000