In [1]:
import pandas as pd #Series Object
s1=pd.Series([1,2,3,4])

In [2]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
import numpy as np
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
type(s1)

pandas.core.series.Series

In [8]:
ar.ndim

2

In [5]:
type(ar)

numpy.ndarray

In [9]:
s2=pd.Series([1,2,3,4], index=['a','b','c','d'])

In [51]:
[s2]

[a    1
 b    2
 c    3
 d    4
 dtype: int64]

In [18]:
data=[[1,2,3,4],[5,6,7,8]]
df1=pd.DataFrame(data)
df1

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [28]:
dct={"id":[1,2,3,4],"name":["hello","world","helloworld","world"]}
df2=pd.DataFrame(dct)
dct

{'id': [1, 2, 3, 4], 'name': ['hello', 'world', 'helloworld', 'world']}

In [25]:
dct

{'id': [1, 2, 3, 4], 'name': ['hello', 'world', 'helloworld', 'world']}

In [26]:
df2=pd.DataFrame(dct)

In [27]:
df2

   id        name
0   1       hello
1   2       world
2   3  helloworld
3   4       world

In [38]:
dct={"Fruits":["Apple","Mango","Orange"],"count":[10,100,500]}
df2=pd.DataFrame(dct)
df2

   Fruits  count
0   Apple     10
1   Mango    100
2  Orange    500

In [30]:
dct

{'Fruits': ['Apple', 'Mango', 'Orange'], 'count': [10, 100, 500]}

In [31]:
dct

{'Fruits': ['Apple', 'Mango', 'Orange'], 'count': [10, 100, 500]}

In [34]:
dct={"Fruits":["Apple","Mango","Orange"],"count":[10,100,500]}

In [35]:
dct

{'Fruits': ['Apple', 'Mango', 'Orange'], 'count': [10, 100, 500]}

In [36]:
df2=pd.DataFrame(dct)

In [37]:
df2

   Fruits  count
0   Apple     10
1   Mango    100
2  Orange    500

In [53]:
SO=pd.Series([6,12,13,14],index=["a","b","c","d"])
df3=pd.DataFrame([SO])
df3

   a   b   c   d
0  6  12  13  14

In [44]:
df3=pd.DataFrame(SO)

In [45]:
df3

    0
a   6
b  12
C  13
d  14

In [69]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])
df6=pd.DataFrame(ar2,columns=["c1","c2","c3","c4"])
df6

   c1  c2  c3  c4
0   1   2   3   4
1   5   6   7   8

In [70]:
df6=pd.DataFrame(ar2)

In [71]:
df6=df6.rename(columns={"c1":"column1","c2":"column2","c3":"column3","c4":"column4"})

In [72]:
df6

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [73]:
df6.index=["r1","r2"]

In [74]:
df6

    0  1  2  3
r1  1  2  3  4
r2  5  6  7  8

In [75]:
dct={
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']}

In [78]:
df1=pd.DataFrame(dct)

In [79]:
df1

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

In [80]:
dct2={'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']}

In [81]:
df2=pd.DataFrame(dct2)

In [82]:
df2

   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5

In [83]:
pd.merge(df1,df2,on='subject_id',how='left') # left join

   id_x  Name_x subject_id  id_y Name_y
0     1    Alex       sub1   NaN    NaN
1     2     Amy       sub2   1.0  Billy
2     3   Allen       sub4   2.0  Brian
3     4   Alice       sub6   4.0  Bryce
4     5  Ayoung       sub5   5.0  Betty

In [85]:
pd.merge(df1,df2,on='subject_id',how='right') # right join

   id_x  Name_x subject_id  id_y Name_y
0   2.0     Amy       sub2     1  Billy
1   3.0   Allen       sub4     2  Brian
2   NaN     NaN       sub3     3   Bran
3   4.0   Alice       sub6     4  Bryce
4   5.0  Ayoung       sub5     5  Betty

In [86]:
pd.merge(df1,df2,on='subject_id',how='inner') # inner join

   id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty

In [87]:
pd.merge(df1,df2,left_on='subject_id',right_on='sub',how='inner') # if we have column name different in two tables

KeyError: 'sub'

In [88]:
pd.merge(df1,df2,on=['id','subject_id'],how='inner') # if we want to join on multiple columns

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty

In [89]:
pd.merge(pd.merge(df1,df2,on='subject_id',how='inner'),df3,on='join colu',how='left') # if we want to join multiple tables

KeyError: 'join colu'

In [91]:
dataset=pd.read_csv("mtcars2.csv")

In [92]:
dataset

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [93]:
dataset.count()

S.No          32
Unnamed: 1    32
mpg           32
cyl           32
disp          32
hp            32
drat          32
wt            32
qsec          29
vs            32
am            32
gear          32
carb          32
dtype: int64

In [94]:
dataset.head(4)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1

In [95]:
dataset.tail(2)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.57,14.6,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.78,18.6,1,1,4,2

In [96]:
dataset.shape()

TypeError: 'tuple' object is not callable

In [98]:
dataset.shape # rows and cols

(32, 13)

In [99]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S.No        32 non-null     int64
 1   Unnamed: 1  32 non-null     object
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64
 10  am          32 non-null     int64
 11  gear        32 non-null     int64
 12  carb        32 non-null     int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB

In [100]:
dataset.mean()

S.No     16.500000
mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.674828
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [101]:
dataset['mpg'].mean()

20.090624999999996

In [103]:
dataset['mpg'].median()

19.2

In [104]:
dataset['mpg'].count()

32

In [105]:
dataset['mpg'].min()

10.4

In [106]:
dataset['mpg'].max()

33.9

In [107]:
dataset.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [108]:
dataset['hp']

0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64

In [109]:
dataset.iloc[:,4]

0     160.0
1     160.0
2     108.0
3     258.0
4     360.0
5     225.0
6     360.0
7     146.7
8     140.8
9     167.6
10    167.6
11    275.8
12    275.8
13    275.8
14    472.0
15    460.0
16    440.0
17     78.7
18     75.7
19     71.1
20    120.1
21    318.0
22    304.0
23    350.0
24    400.0
25     79.0
26    120.3
27     95.1
28    351.0
29    145.0
30    301.0
31    121.0
Name: disp, dtype: float64

In [124]:
dataset['hp']='110'

In [113]:
dataset.iloc[5,5]

110

In [126]:
dataset.iloc[0:5,5]

0    110
1    110
2    110
3    110
4    110
Name: hp, dtype: object

In [118]:
dataset.iloc[1:5,5:9]

    hp  drat     wt   qsec
1  110  3.90  2.875  17.02
2  110  3.85  2.320  18.61
3  110  3.08  3.215  19.44
4  110  3.15  3.440  17.02

In [120]:
dataset.iloc[[1,2,4],[5,7,12]]

    hp     wt  carb
1  110  2.875     4
2  110  2.320     1
4  110  3.440     2

In [121]:
dataset

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,110,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,110,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,110,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,110,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,110,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,110,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,110,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,110,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,110,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,110,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,110,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,110,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,110,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,110,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,110,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,110,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,110,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,110,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,110,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,110,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,110,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,110,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,110,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,110,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,110,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,110,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,110,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,110,4.11,2.780,18.60,1,1,4,2

In [122]:
dataset['Unnamed: 1'].value_counts()

Ford Pantera L         1
Fiat X1-9              1
Merc 450SE             1
Mazda RX4              1
Toyota Corona          1
Cadillac Fleetwood     1
Camaro Z28             1
Ferrari Dino           1
Hornet 4 Drive         1
Pontiac Firebird       1
Honda Civic            1
AMC Javelin            1
Merc 280               1
Merc 280C              1
Fiat 128               1
Merc 450SLC            1
Volvo 142E             1
Toyota Corolla         1
Hornet Sportabout      1
Merc 230               1
Porsche 914-2          1
Dodge Challenger       1
Chrysler Imperial      1
Duster 360             1
Maserati Bora          1
Lotus Europa           1
Lincoln Continental    1
Valiant                1
Mazda RX4 Wag          1
Datsun 710             1
Merc 240D              1
Merc 450SL             1
Name: Unnamed: 1, dtype: int64

In [129]:
dataset['qsec'].fillna(10, inpalce=True)

TypeError: fillna() got an unexpected keyword argument 'inpalce'

In [130]:
dataset

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,110,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,110,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,110,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,110,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,110,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,110,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,110,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,110,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,110,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,110,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,110,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,110,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,110,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,110,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,110,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,110,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,110,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,110,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,110,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,110,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,110,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,110,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,110,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,110,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,110,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,110,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,110,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,110,4.11,2.780,18.60,1,1,4,2

In [133]:
dataset.iloc[5:]

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,110,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,110,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,110,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,110,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,110,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,110,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,110,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,110,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,110,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,110,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,110,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,110,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,110,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,110,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,110,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,110,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,110,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,110,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,110,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,110,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,110,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,110,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,110,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,110,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,110,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,110,4.11,2.780,18.60,1,1,4,2

In [135]:
dataset[:6]

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,110,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,110,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1

In [136]:
dataset.iloc[:,6]

0     3.90
1     3.90
2     3.85
3     3.08
4     3.15
5     2.76
6     3.21
7     3.69
8     3.92
9     3.92
10    3.92
11    3.07
12    3.07
13    3.07
14    2.93
15    3.00
16    3.23
17    4.08
18    4.93
19    4.22
20    3.70
21    2.76
22    3.15
23    3.73
24    3.08
25    4.08
26    4.43
27    3.77
28    4.22
29    3.62
30    3.54
31    4.11
Name: drat, dtype: float64

In [138]:
dataset.iloc[5].transpose()

S.No                6
Unnamed: 1    Valiant
mpg              18.1
cyl                 6
disp            225.0
hp                110
drat             2.76
wt               3.46
qsec              NaN
vs                  1
am                  0
gear                3
carb                1
Name: 5, dtype: object

In [139]:
dataset

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,110,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,110,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,110,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,110,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,110,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,110,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,110,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,110,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,110,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,110,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,110,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,110,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,110,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,110,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,110,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,110,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,110,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,110,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,110,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,110,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,110,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,110,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,110,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,110,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,110,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,110,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,110,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,110,4.11,2.780,18.60,1,1,4,2

In [145]:
dataset.iloc[1:5,2:4]

    mpg  cyl
1  21.0    6
2  22.8    4
3  21.4    6
4  18.7    8

In [146]:
dataset.iloc[[1,2,4],[1,2,3]]

          Unnamed: 1   mpg  cyl
1      Mazda RX4 Wag  21.0    6
2         Datsun 710  22.8    4
4  Hornet Sportabout  18.7    8

In [147]:
dataset

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,110,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,110,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,110,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,110,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,110,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,110,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,110,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,110,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,110,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,110,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,110,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,110,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,110,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,110,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,110,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,110,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,110,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,110,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,110,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,110,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,110,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,110,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,110,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,110,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,110,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,110,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,110,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,110,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,110,4.11,2.780,18.60,1,1,4,2

In [149]:
dataset.iloc[0,2]

21.0

In [152]:
dataset.iloc[[1,5,6],[1,2,3]]

      Unnamed: 1   mpg  cyl
1  Mazda RX4 Wag  21.0    6
5        Valiant  18.1    6
6     Duster 360  14.3    8

In [153]:
dataset.iloc[2:7,5:8]

    hp  drat     wt
2  110  3.85  2.320
3  110  3.08  3.215
4  110  3.15  3.440
5  110  2.76  3.460
6  110  3.21  3.570

In [158]:
class Dog:
    def add_one(self, x):
        return x + 1
    def bark(self):
        print("bark")

d = Dog()
d.bark()
d.add_one(5)

bark

6

In [170]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def get_name(self):
        return self.name
    def get_age(self):
        return self.age
d = Dog("Tim",34)
print(d.get_name())
print(d.get_age())
d2 = Dog("Bill",12)
print(d2.get_name())
print(d2.get_age())

Tim
34
Bill
12

In [178]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def get_name(self):
        return self.name
    def get_age(self):
        return self.age
    def set_age(self, age):
        self.age = age
d = Dog("Tim",34)
print(d.get_name())
print(d.get_age())
d.set_age(23)
print(d.get_age())

Tim
34
23